server:
  port: 8080
spring:
  application:
 name: "DifferentRoads"
  devtools:
    h2:
    console:
      enabled: true
      path: "/h2"
  profiles:
 include: null
  kafka:
    bootstrap-servers: localhost:9092 # Replace with your Kafka bootstrap servers
    consumer:
      group-id: my-consumer-group # Replace with your desired consumer group id
      enabled: true # This should be at the same indentation level as group-id
